apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # base64 encoded value for 'mongoadmin'
  mongo-root-password: cGFzc3dvcmQxMjM=  # base64 encoded value for 'password123'
